apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-webapp
  labels:
    app: react-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-webapp
  template:
    metadata:
      labels:
        app: react-webapp
    spec:
      containers:
      - name: react-webapp
        image: sushmita2210/react-nginx-ui:version2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
