apiVersion: v1
kind: Service
metadata:
  name: java-webapp-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: java-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
